import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
from pylab import plot, show, figure, imshow
import soundfile as sf
import pyrubberband as pyrb
import essentia
import essentia.streaming as ess
import tkinter as tk
from tkinter import ttk

# testing variables
test_filename = "sample audios/" + "[Ambient] #3 - Aphex Twin.wav"
test_keyscale = "F# minor"

# sample audio data
sample_audios = [
    "[Ambient] #3 - Aphex Twin.wav",
    "[Ambient] An Ending (Ascent) - Brian Eno.wav",
    "[Blues] Cross Road Blues - Robert Johnson.wav",
    "[Blues] The Thrill is Gone - B.B. King.wav",
    "[Classical] 12 Études, Op. 25, No. 11 in A Minor Winter Wind - Frédéric Chopin.wav",
    "[Classical] Serenade for Strings, Op. 48, II. Waltz. Moderato - Pyotr Ilyich Tchaikovsky.wav",
    "[Country] I Walk the Line - Johnny Cash.wav",
    "[Country] Jolene - Dolly Parton.wav",
    "[Dance] Lose Control - Meduza.wav",
    "[Dance] One More Time - Daft Punk.wav",
    "[Easy Listening] Can't Help Falling in Love - Elvis Presley.wav",
    "[Easy Listening] Perfect - Ed Sheeran.wav",
    "[Electronic] Bangarang - Skrillex.wav",
    "[Electronic] Strobe - Deadmau5.wav",
    "[Folk] Fast Car - Tracy Chapman.wav",
    "[Folk] The Times They Are A-Changin' - Bob Dylan.wav",
    "[Hip-hop] Money Trees - Kendrick Lamar.wav",
    "[Hip-hop] ss - Ken Carson.wav",
    "[Industrial & Noise] The Beautiful People - Marilyn Manson.wav",
    "[Industrial & Noise] The Downward Spiral - Nine Inch Nails.wav",
    "[Jazz] Easy Lovers - Piero Piccioni.wav",
    "[Jazz] Polka Dots and Moonbeams - Chet Baker.wav",
    "[Metal] Master of Puppets - Metallica.wav",
    "[Metal] Raining Blood - Slayer.wav",
    "[New Age] Only Time - Enya.wav",
    "[New Age] She Trails Flowers - Neutron 9000.wav",
    "[Pop] Payphone - Maroon 5.wav",
    "[Pop] yes, and? - Ariana Grande.wav",
    "[Psychedelia] Lucy in the Sky with Diamonds - The Beatles.wav",
    "[Psychedelia] My Fun - Suki Waterhouse.wav",
    "[Punk] I Write Sins Not Tragedies - Panic! At The Disco.wav",
    "[Punk] King For A Day - Pierce The Veil.wav",
    "[R&B] Can't Let Go - Amerie.wav",
    "[R&B] Snooze - SZA.wav",
    "[Reggae] Praise Jah In The Moonlight - YG Marley.wav",
    "[Reggae] Three Little Birds - Bob Marley & The Wailers.wav",
    "[Regional - Afro] OZEBA - Rema.wav",
    "[Regional - Afro] Ye - Burna Boy.wav",
    "[Regional - Bollywood] Kala Chashma - Prem & Hardeep.wav",
    "[Regional - Bollywood] Tu Meri - Vishal Dadlani.wav",
    "[Regional - K-Pop] Michyeo - Lee Jung Hyun.wav",
    "[Regional - K-Pop] Super Shy - NewJeans.wav",
    "[Regional - Reggaeton] Gasolina - Daddy Yankee.wav",
    "[Regional - Reggaeton] Me Porto Bonito - Bad Bunny.wav",
    "[Regional - Tamil Kuthu] Danga Maari Oodhari - Harris Jayaraj.wav",
    "[Regional - Tamil Kuthu] Naakka Mukka - Vijay Antony.wav",
    "[Rock] Don't Stop Me Now - Queen.wav",
    "[Rock] Stairway to Heaven - Led Zeppelin.wav"
]

expected_keyscale_dict = {
    "[Ambient] #3 - Aphex Twin.wav": "F# minor",
    "[Ambient] An Ending (Ascent) - Brian Eno.wav": "Ab major",
    "[Blues] Cross Road Blues - Robert Johnson.wav": "B minor",
    "[Blues] The Thrill is Gone - B.B. King.wav": "B minor",
    "[Classical] 12 Études, Op. 25, No. 11 in A Minor Winter Wind - Frédéric Chopin.wav": "A minor",
    "[Classical] Serenade for Strings, Op. 48, II. Waltz. Moderato - Pyotr Ilyich Tchaikovsky.wav": "G major",
    "[Country] I Walk the Line - Johnny Cash.wav": "F major",
    "[Country] Jolene - Dolly Parton.wav": "C# minor",
    "[Dance] Lose Control - Meduza.wav": "C minor",
    "[Dance] One More Time - Daft Punk.wav": "D major",
    "[Easy Listening] Can't Help Falling in Love - Elvis Presley.wav": "F# minor",
    "[Easy Listening] Perfect - Ed Sheeran.wav": "Ab major",
    "[Electronic] Bangarang - Skrillex.wav": "G minor",
    "[Electronic] Strobe - Deadmau5.wav": "Ab minor",
    "[Folk] Fast Car - Tracy Chapman.wav": "A major",
    "[Folk] The Times They Are A-Changin' - Bob Dylan.wav": "G major",
    "[Hip-hop] Money Trees - Kendrick Lamar.wav": "E minor",
    "[Hip-hop] ss - Ken Carson.wav": "C# minor",
    "[Industrial & Noise] The Beautiful People - Marilyn Manson.wav": "A minor",
    "[Industrial & Noise] The Downward Spiral - Nine Inch Nails.wav": "E minor",
    "[Jazz] Easy Lovers - Piero Piccioni.wav": "F major",
    "[Jazz] Polka Dots and Moonbeams - Chet Baker.wav": "D minor",
    "[Metal] Master of Puppets - Metallica.wav": "E minor",
    "[Metal] Raining Blood - Slayer.wav": "Eb major",
    "[New Age] Only Time - Enya.wav": "Eb major",
    "[New Age] She Trails Flowers - Neutron 9000.wav": "C major",
    "[Pop] Payphone - Maroon 5.wav": "B major",
    "[Pop] yes, and? - Ariana Grande.wav": "Bb minor",
    "[Psychedelia] Lucy in the Sky with Diamonds - The Beatles.wav": "D major",
    "[Psychedelia] My Fun - Suki Waterhouse.wav": "E major",
    "[Punk] I Write Sins Not Tragedies - Panic! At The Disco.wav": "A minor",
    "[Punk] King For A Day - Pierce The Veil.wav": "B minor",
    "[R&B] Can't Let Go - Amerie.wav": "C minor",
    "[R&B] Snooze - SZA.wav": "D minor",
    "[Reggae] Praise Jah In The Moonlight - YG Marley.wav": "F# minor",
    "[Reggae] Three Little Birds - Bob Marley & The Wailers.wav": "A major",
    "[Regional - Afro] OZEBA - Rema.wav": "D minor",
    "[Regional - Afro] Ye - Burna Boy.wav": "F minor",
    "[Regional - Bollywood] Kala Chashma - Prem & Hardeep.wav": "D minor",
    "[Regional - Bollywood] Tu Meri - Vishal Dadlani.wav": "Ab major",
    "[Regional - K-Pop] Michyeo - Lee Jung Hyun.wav": "D minor",
    "[Regional - K-Pop] Super Shy - NewJeans.wav": "F minor",
    "[Regional - Reggaeton] Gasolina - Daddy Yankee.wav": "F minor",
    "[Regional - Reggaeton] Me Porto Bonito - Bad Bunny.wav": "C# minor",
    "[Regional - Tamil Kuthu] Danga Maari Oodhari - Harris Jayaraj.wav": "D minor",
    "[Regional - Tamil Kuthu] Naakka Mukka - Vijay Antony.wav": "D minor",
    "[Rock] Don't Stop Me Now - Queen.wav": "F major",
    "[Rock] Stairway to Heaven - Led Zeppelin.wav": "A minor"
}

expected_bpm_dict = {
    "[Ambient] #3 - Aphex Twin.wav": 115,
    "[Ambient] An Ending (Ascent) - Brian Eno.wav": 129,
    "[Blues] Cross Road Blues - Robert Johnson.wav": 96,
    "[Blues] The Thrill is Gone - B.B. King.wav": 90,
    "[Classical] 12 Études, Op. 25, No. 11 in A Minor Winter Wind - Frédéric Chopin.wav": 120,
    "[Classical] Serenade for Strings, Op. 48, II. Waltz. Moderato - Pyotr Ilyich Tchaikovsky.wav": 60,
    "[Country] I Walk the Line - Johnny Cash.wav": 106,
    "[Country] Jolene - Dolly Parton.wav": 110,
    "[Dance] Lose Control - Meduza.wav": 124,
    "[Dance] One More Time - Daft Punk.wav": 123,
    "[Easy Listening] Can't Help Falling in Love - Elvis Presley.wav": 68,
    "[Easy Listening] Perfect - Ed Sheeran.wav": 64,
    "[Electronic] Bangarang - Skrillex.wav": 110,
    "[Electronic] Strobe - Deadmau5.wav": 64,
    "[Folk] Fast Car - Tracy Chapman.wav": 104,
    "[Folk] The Times They Are A-Changin' - Bob Dylan.wav": 86,
    "[Hip-hop] Money Trees - Kendrick Lamar.wav": 72,
    "[Hip-hop] ss - Ken Carson.wav": 138,
    "[Industrial & Noise] The Beautiful People - Marilyn Manson.wav": 72,
    "[Industrial & Noise] The Downward Spiral - Nine Inch Nails.wav": 101,
    "[Jazz] Easy Lovers - Piero Piccioni.wav": 138,
    "[Jazz] Polka Dots and Moonbeams - Chet Baker.wav": 124,
    "[Metal] Master of Puppets - Metallica.wav": 105,
    "[Metal] Raining Blood - Slayer.wav": 89,
    "[New Age] Only Time - Enya.wav": 82,
    "[New Age] She Trails Flowers - Neutron 9000.wav": 115,
    "[Pop] Payphone - Maroon 5.wav": 110,
    "[Pop] yes, and? - Ariana Grande.wav": 119,
    "[Psychedelia] Lucy in the Sky with Diamonds - The Beatles.wav": 95,
    "[Psychedelia] My Fun - Suki Waterhouse.wav": 88,
    "[Punk] I Write Sins Not Tragedies - Panic! At The Disco.wav": 85,
    "[Punk] King For A Day - Pierce The Veil.wav": 112,
    "[R&B] Can't Let Go - Amerie.wav": 83,
    "[R&B] Snooze - SZA.wav": 71,
    "[Reggae] Praise Jah In The Moonlight - YG Marley.wav": 125,
    "[Reggae] Three Little Birds - Bob Marley & The Wailers.wav": 74,
    "[Regional - Afro] OZEBA - Rema.wav": 74,
    "[Regional - Afro] Ye - Burna Boy.wav": 101,
    "[Regional - Bollywood] Kala Chashma - Prem & Hardeep.wav": 106,
    "[Regional - Bollywood] Tu Meri - Vishal Dadlani.wav": 128,
    "[Regional - K-Pop] Michyeo - Lee Jung Hyun.wav": 132,
    "[Regional - K-Pop] Super Shy - NewJeans.wav": 75,
    "[Regional - Reggaeton] Gasolina - Daddy Yankee.wav": 96,
    "[Regional - Reggaeton] Me Porto Bonito - Bad Bunny.wav": 91,
    "[Regional - Tamil Kuthu] Danga Maari Oodhari - Harris Jayaraj.wav": 75,
    "[Regional - Tamil Kuthu] Naakka Mukka - Vijay Antony.wav": 99,
    "[Rock] Don't Stop Me Now - Queen.wav": 79,
    "[Rock] Stairway to Heaven - Led Zeppelin.wav": 83
}

